### ISSUE TITLE
Custom CSS may move bottom that makes it available

### ISSUE THREAD

**Issue by minosss** [BoostIO/Boostnote#2507]
If I add some style to custom CSS. eg: `body`

```css
body {
 font-family: 'Source Sans Pro';
}
```

This will be overridden by the following style.

https://github.com/BoostIO/Boostnote/blob/71ae42056feadb823ecb4a4402dc83756f295e8c/browser/components/MarkdownPreview.js#L83-L90
